spring.application.name=ResumeAnalyzer
spring.datasource.url=jdbc:mysql://localhost:3306/resume?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=2022678xc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
deepseek.api-key=sk-5e074c7d14ea4f3daff916081d61b791
deepseek.url=https://api.deepseek.com/v1/chat/completions

# MinIO ??
minio.endpoint=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucketName=my-bucket

# ?????????
spring.servlet.multipart.max-file-size=10MB
# ???????????
spring.servlet.multipart.max-request-size=10MB
# DataSource Config
